name: pancake
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy=1.26.3
  - statsmodels=0.14.0
  # - jupyterlab=4.0.11
  - web3=6.15.1
  - pip
  - pip:
      - retrying=1.3.4
      - streamlit=1.31.1
      - toml=0.10.2