name: pancake
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - requests
  - statsmodels
  # - jupyterlab
  - web3
  - pip
  - pip:
      - retrying
      - streamlit
      - toml